### ISSUE TITLE
Scream Fortress Merasmissions/Tough Break contracts don't work :(

### ISSUE THREAD

**Issue by jerclarke** [sirgrey/SirHUD#1]
Hey man, LOVE this HUD, nothing seems to come close in terms of elegance for Spy as well as Medic in particular, love the Uber bar. 

Unlike some other HUDs where the current contracts don't work at all Sir.hud seems to almost work, and I see the folder-notification and can open it, but inside I can't see the contracts. 

Any chance you could fix the hud for SF 2015 and hopefully future contracts? Hate having to switch to 7hud for missions :P

**Comment by jerclarke** [comment]
Unfortunately but predictably the same applies to the new contracts for Tough Break. The contracts menu opens and I can see the new background art but I can't see any of the contracts.

**Comment by sirgrey** [comment]
I have just added support for Tough Break update today.

**Comment by jerclarke** [comment]
Thanks!
